### ISSUE TITLE
docker 启动出现错误：panic: failed to connect database

### ISSUE THREAD

**Issue by mxue12138** [hujinbo23/dst-admin-go#58]
大佬，求救！！！呜呜呜！！！

使用 docker 启动服务，前面都正常，到最后出现这个错误
系统：CentOS Linux release 7.9.2009 (Core)（6.0.2-1.el7.elrepo.x86_64）
配置：2H4G
目录权限正常777，磁盘空间正常，selinux及其他都关闭了，dst-admin-go.log、dst-db、DoNotStarveTogether 这三个目录都是空的

启动命令有点乱，没用 docker-compose
```
docker run -d -p 8082:8082 -v /root/dst/DoNotStarveTogether:/root/.klei/DoNotStarveTogether -v /root/dst/backup:/app/backup -v /root/dst/mod:/app/mod -v /root/dst/dst-db:/app/dst-db -v /root/dst/dst-admin-go.log:/app/dst-admin-go.log -v /root/dst/dst-dedicated-server:/app/dst-dedicated-server -v /root/dst/steamcmd:/app/steamcmd hujinbo23/dst-admin-go
```

```
Not found Dont Starve Together Sever, start to installing, try: 1
tid(11) burning pthread_key_t == 0 so we never use it
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/root/Steam/logs/stderr.txt'
Logging directory: '/root/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x11) preallocating, progress: 32.80 (1120309542 / 3415352296)
 ..................................................................................................
 Update state (0x81) verifying update, progress: 96.58 (3298534181 / 3415352296)
 Update state (0x101) committing, progress: 19.03 (649893720 / 3415352296)
 Update state (0x101) committing, progress: 38.85 (1326835985 / 3415352296)
Success! App '343050' fully installed.
SteamCMD installed at /app/steamcmd
SteamDST server installed at /app/dst-dedicated-server
home path: /root
2024/02/01 08:56:52 config:  &{8082  dst-db       {true 5 10} }
panic: failed to connect database

goroutine 1 [running]:
dst-admin-go/bootstrap.initDB()
	C:/Users/paratera/Desktop/我的/饥荒面板/dst-admin-go/bootstrap/init.go:51 +0x558
dst-admin-go/bootstrap.Init()
	C:/Users/paratera/Desktop/我的/饥荒面板/dst-admin-go/bootstrap/init.go:37 +0x25
main.main()
	C:/Users/paratera/Desktop/我的/饥荒面板/dst-admin-go/main.go:17 +0x1d

```

**Comment by hujinbo23** [comment]
你容器外有dst-db 文件吗 自己放一个 初始化完整的 dst-db 文件。这个文件没必要映射里面都些日志和定时任务信息，数据不重要
